ocf/slackbridge

- slackbridge/bots.py
- slackbridge/factories.py
A start to resolving #15. Regex searches a message for usernames enclosed in <@...> and replaces that substring with their username before sending the message to irc.
> Bridge usernames typed in chat correctly from Slack -> IRC

- slackbridge/bots.py
- slackbridge/factories.py
Reverts ocf/slackbridge#28
Missing a line. Crashing slackbridge.
> Revert "Bridge usernames typed in chat correctly from Slack -> IRC"

- slackbridge/bots.py
> Mirror changes in channel topic from IRC to Slack.

- slackbridge/bots.py
Stops channel from causing a KeyError as not all events have a channel attribute.
> Prevent channel KeyError

- slackbridge/bots.py
- slackbridge/factories.py
- slackbridge/messages.py
This simplifies the storage of the mappings of users and channels to store them in the `IRCBot` class instead of passing them around everywhere. As @kkuehler mentioned on IRC/Slack to me already, the channel mapping stuff could be done even earlier, in `main.py` or something, but the user mapping can't be done until the factories start, because it maps user IDs to bots, which aren't available until later.
> Refactor user and channel storage

- slackbridge/bots.py
- slackbridge/factories.py
- slackbridge/utils.py
IRC users are used to pinging a user simply by typing a nick.
This patch provides that functionality, albeit in a
heavy-handed manner.
Fixes #47
> IRC -> Slack tagging

- slackbridge/bots.py
- slackbridge/factories.py
- slackbridge/utils.py
#51 
Adds a global lookup for bots much like 'users', and modifies the `format_irc_message` method to also lookup bots.
> Fix crash from mentioning @irc-bridge

- slackbridge/bots.py
- slackbridge/factories.py
- slackbridge/messages.py
#12 
I'm planning to add support for messaging users privately.
**On the IRC -> Slack side:**
Sender /msg's the {user}-slack bot. The message is prepended with the sender's nick and sent via a direct Slack IM Channel from irc-bridge to the Slack user.
on IRC: `/msg jaw-slack testing pm`
on Slack from irc-bridge: `jaw: testing pm`
**On the Slack -> IRC side:**
Current plan is to allow the Slack user to message irc-bridge directly in the format [user]:[message] which will redirect it to the appropriate user on IRC.
I'm also exploring options to use Slack's threads for this feature, but this means we'll have to find a way to handle bot restarts.
> add support for private messaging

- Makefile
- mypy.ini
- slackbridge/bots.py
- slackbridge/factories.py
- slackbridge/main.py
- slackbridge/messages.py
- slackbridge/utils.py
This makes mypy checking stricter (and also moves to using a config
file). The only question I faced when working on this was how to
represent the JSON responses of the Slack API. I decided on `Dict[str,
Any]`, which should be sufficient for now. Later if interested it would
be a fun project to convert these to
[TypedDict](https://mypy.readthedocs.io/en/latest/more_types.html#typeddict),
which would give us a bit more type safety. I will open an issue on that
once this is merged (and would happy to mentor that).
>  Intial pass at type annotating slackbridge

- Makefile
- mypy.ini
- slackbridge/bots.py
- slackbridge/factories.py
- slackbridge/main.py
- slackbridge/messages.py
- slackbridge/utils.py
The main 2 differences are in the last commit, namely use that sweet `from __future__ import annotations` and this fixes an import cycle that would otherwise be introduced by importing the IRCBot types into the messages file.
> Strict mypy take 2

- slackbridge/messages.py
This should stop crashes on video uploads by checking if the `thumb_1024` attribute exists before trying to access it.
(finally pushed the fix I mentioned back in January lol: https://moffle.fuqu.jp/ocf/%23rebuild/20190112#L444)
> Don't crash on video uploads (closes #74)

- slackbridge/bots.py
This should remove those pesky topic updates in #ocf whenever slackbridge is restarted or being developed by just not updating the topic if only formatting differs between the two.
> Don't update the channel topic if only formatting differs

- slackbridge/main.py
Previously when gathering all channels using the old `channels.list` function, it would pick up channels with no members. The new `conversations.list` function does not have this problem.
I am also not sure how to best test if this change caused anything to go wrong. It seemed okay on dev-irc, but I am not confident without approval.
> Updated legacy api call

- README.md
- slackbridge.conf.sample
This adds a sample config file (at `slackbridge.conf.sample`) to show the structure of it and briefly explain what each field is used for.
> Add sample slackbridge.conf file (closes #88)

- slackbridge/main.py
#decal-general (and apparently 11 other channels) were not getting bridged because they were cut off by pagination in Slack's API. This resolves the issue.
> increase channel list limit to 500

- slackbridge/main.py
Their API does not like this. However, we still want to keep the bot
in the channel to mirror messages.
closes #101
> Skip querying Slack for members of empty channels

- slackbridge/bots.py
[the old one will stop working in November 2020](https://api.slack.com/changelog/2020-01-deprecating-antecedents-to-the-conversations-api)
they're mostly drop in replacements so I don't expect much to break
> use slack's new api

- Dockerfile
- services/bridge/log/run
- services/bridge/run
I tested by building the image locally and running it (needed to specify a config file though to get it to work, so I did need to modify it to do that for actual testing. Seemed to all work fine though
> Log directly to stdout, remove runit/services

- slackbridge/main.py
This adds some pagination for the `conversations.members` call in particular, but more general pagination is available in slackclient 2.x which we are not on yet (#78), and might never upgrade to if this project goes away (#107).
> Fix slackbridge crash above 500 users

- slackbridge/bots.py
Slack deprecated `rtm.start` and as a result the bot no longer connected to RTM correctly. This connects via `rtm.connect` instead which seems to be working fine with no further changes.
https://api.slack.com/changelog/2021-10-rtm-start-to-stop
> Use rtm.connect instead of rtm.start
